### ISSUE TITLE
新版本查成分报错

### ISSUE THREAD

**Issue by yoiyami96** [noneplugin/nonebot-plugin-ddcheck#14]
06-15 20:03:43 [WARNING] src | Traceback (most recent call last):
  File "C:\Users\cyy19\Downloads\software\amiya\bot\.\src\plugins\ddcheck\__init__.py", line 33, in _
    res = await get_reply(text)
  File "C:\Users\cyy19\Downloads\software\amiya\bot\.\src\plugins\ddcheck\data_source.py", line 186, in get_reply
    template = env.get_template("info.html")
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1000, in get_template
    return self._load_template(name, globals)
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 959, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: info.html

**Comment by MeetWq** [comment]
你是pip装的还是手动装的

**Comment by yoiyami96** [comment]
> 你是pip装的还是手动装的

手动装的，换了pip安装能用了，两者有啥不一样吗

**Comment by MeetWq** [comment]
现在一样了，之前忘记push了

**Comment by yoiyami96** [comment]
> 现在一样了，之前忘记push了

手动安装依然会报错，我看其他issue说可能是和bilibili_api或者其他插件有冲突，是这个原因吗

**Comment by MeetWq** [comment]
手动装的时候有下 `template` 文件夹吗

**Comment by yoiyami96** [comment]
> 手动装的时候有下 `template` 文件夹吗

焯，破案了，我以为这只是个示例就删了。抱歉打扰大佬这么久！
