### ISSUE TITLE
[BUG] UnicodeEncodeError: 'ascii' codec can't encode character '\u2026' in position 512: ordinal not in range(128)

### ISSUE THREAD

**Issue by MasterYuan418** [noneplugin/nonebot-plugin-ddcheck#25]
环境：Ubuntu 20.04LTS + Python 3.8
复现次数：每次
堆栈跟踪：
```
02-04 13:25:44 [WARNING] nonebot_plugin_ddcheck | Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot_plugin_ddcheck/__init__.py", line 54, in _
    result = await get_reply(text)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot_plugin_ddcheck/data_source.py", line 177, in get_reply
    medals = await get_medals(uid)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot_plugin_ddcheck/data_source.py", line 131, in get_medals
    resp = await client.get(url, params=params, headers=headers)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/httpx/_client.py", line 1520, in request
    request = self.build_request(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/httpx/_client.py", line 349, in build_request
    headers = self._merge_headers(headers)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/httpx/_client.py", line 416, in _merge_headers
    merged_headers.update(headers)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/httpx/_models.py", line 200, in update
    headers = Headers(headers)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/httpx/_models.py", line 71, in __init__
    self._list = [
  File "/home/ubuntu/.local/lib/python3.8/site-packages/httpx/_models.py", line 75, in <listcomp>
    normalize_header_value(v, encoding),
  File "/home/ubuntu/.local/lib/python3.8/site-packages/httpx/_utils.py", line 55, in normalize_header_value
    return value.encode(encoding or "ascii")
UnicodeEncodeError: 'ascii' codec can't encode character '\u2026' in position 512: ordinal not in range(128)
```

**Comment by MeetWq** [comment]
检查一下cookie设置的对不对

**Comment by MasterYuan418** [comment]
已检查Cookie，在`.env.dev`中有如下配置：
```
bilibili_cookie="SESSDATA=***********"
```
且`SESSDATA`是从`www.bilibili.com`抓到的

**Comment by MasterYuan418** [comment]
抱歉，程序已恢复正常。
