### ISSUE TITLE
查成分出错

### ISSUE THREAD

**Issue by CaffuChin0** [noneplugin/nonebot-plugin-ddcheck#27]
![QQ截图20230213093352](https://user-images.githubusercontent.com/47897127/218351710-9117ad5b-b28b-409c-82ca-4d5a35b6ef55.png)

是否我饼干设置出问题，我翻阅https://github.com/noneplugin/nonebot-plugin-ddcheck/issues/18设置了SESSDATA后依旧无法查询

bilibili_cookie: str = "SESSDATA=c05996bf%2C1691803051%2C2c23c%2A21"

错误信息：
02-13 09:34:55 [WARNING] nonebot_plugin_ddcheck | Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\zhenxun_bot\plugins\nonebot_plugin_ddcheck\__init__.py", line 33, in _
    res = await get_reply(text)
  File "C:\Users\Administrator\Desktop\zhenxun_bot\plugins\nonebot_plugin_ddcheck\data_source.py", line 154, in get_reply
    uid = await get_uid_by_name(name)
  File "C:\Users\Administrator\Desktop\zhenxun_bot\plugins\nonebot_plugin_ddcheck\data_source.py", line 94, in get_uid_by_name
    for user in result["data"]["result"]:
TypeError: 'NoneType' object is not subscriptable

Version:0.1

**Comment by MeetWq** [comment]
我看你的报错，似乎和现在的代码对不上，先更新一下试试

**Comment by CaffuChin0** [comment]
没问题了，谢谢大佬
