### ISSUE TITLE
报错：json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by KawakazeNotFound** [noneplugin/nonebot-plugin-ddcheck#31]
QQ指令如下:
    user:@BotID /查成分439XXXXX
    bot:获取用户信息失败，请检查名称或稍后再试
后台报错如下：
    08-12 15:53:27 [WARNING] nonebot_plugin_ddcheck | Traceback (most recent call last):
  File "/home/kawakaze/qqbot/test/.venv/lib/python3.12/site-packages/nonebot_plugin_ddcheck/data_source.py", line 159, in get_reply
    user_info = await get_user_info(uid)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kawakaze/qqbot/test/.venv/lib/python3.12/site-packages/nonebot_plugin_ddcheck/data_source.py", line 123, in get_user_info
    result = resp.json()
             ^^^^^^^^^^^
  File "/home/kawakaze/qqbot/test/.venv/lib/python3.12/site-packages/httpx/_models.py", line 762, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
=====
配置文件如下：
    .env填写了如下变量：
        bilibili_cookie="SESSDATA=ad19c68a%2C1738840789%2Cba956%2A82CjDV8Mmuyq3Y6_u6qvmGSZvV3s2iYHmljf-1sJNlcDGlXzQWo41rNxrnpa0iimJSZuASVlpNOXdiaDhUSG44QnF1Z1NoXzk2bzVaSG9FZlZ4dlB3Q3RackZMVklUamFhbGtZT2NySmt3TC1zZE1nc0RvYy1wN1F2aERDRG9XQjh2UWpVTmM4aF9nIIEC;"
        .env.dev同理

**Comment by DreamGallery** [comment]
我也一样遇到了这个问题
![image](https://github.com/user-attachments/assets/d79aa7a1-7a2e-43e4-a26c-b20b7324277a)
是B站API变了吗？

**Comment by MeetWq** [comment]
已更新，加了 user-agent，应该能用了

**Comment by Jerry-Z07** [comment]
> 已更新，加了 user-agent，应该能用了

似乎还是不能使用
```
Running AlconnaMatcher(type='', module=nonebot_plugin_ddcheck, lineno=39) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot_plugin_ddcheck/__init__.py", line 57, in _
    uid = await get_uid_by_name(name)
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot_plugin_ddcheck/data_source.py", line 103, in get_uid_by_name
    resp = await bilireq.utils.get(url, params=params, cookies=cookies)
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/bilireq/utils/__init__.py", line 184, in get
    return await request("GET", url, **kwargs)
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/bilireq/utils/__init__.py", line 160, in request
    raw_json: Dict[str, Any] = resp.json()
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/httpx/_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


```
