### ISSUE TITLE
查成分报错

### ISSUE THREAD

**Issue by doiss** [noneplugin/nonebot-plugin-ddcheck#6]
'
2022-05-01 14:18:04 INFO Self: 3521302610, Message 1349497962 from 939671580@[群:232604481]: '查成分11073'
[2022-05-01 14:18:04,553 ddcheck] INFO: Message 1349497962 triggered ddcheck.
2022-05-01 14:18:04 INFO Message 1349497962 triggered ddcheck.
2022-05-01 14:18:04 INFO received event: meta_event.heartbeat
[2022-05-01 14:18:04,572] INFO in __init__: received event: meta_event.heartbeat
2022-05-01 14:18:04 ERROR Task exception was never retrieved
future: <Task finished name='Task-368' coro=<Connection.run() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_connection.py:175> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_connection.py", line 182, in run
    await self._transport.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_transport.py", line 140, in connect
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_transport.py", line 128, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 491, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
[2022-05-01 14:18:04,837 nonebot] WARNING: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\__init__.py", line 43, in ddcheck
    res = await get_reply(text)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\data_source.py", line 184, in get_reply
    return await html_to_pic(content, wait=0, viewport={"width": 100, "height": 100})
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\htmlrender.py", line 159, in html_to_pic
    async with get_new_page(**kwargs) as page:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\browser.py", line 45, in get_new_page
    browser = await get_browser()
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\browser.py", line 40, in get_browser
    return _browser or await init(**kwargs)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\browser.py", line 26, in init
    _playwright = await async_playwright().start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_connection.py", line 182, in run
    await self._transport.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_transport.py", line 140, in connect
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_transport.py", line 128, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 491, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

2022-05-01 14:18:04 WARNING Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\__init__.py", line 43, in ddcheck
    res = await get_reply(text)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\data_source.py", line 184, in get_reply
    return await html_to_pic(content, wait=0, viewport={"width": 100, "height": 100})
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\htmlrender.py", line 159, in html_to_pic
    async with get_new_page(**kwargs) as page:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\browser.py", line 45, in get_new_page
    browser = await get_browser()
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\browser.py", line 40, in get_browser
    return _browser or await init(**kwargs)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\browser.py", line 26, in init
    _playwright = await async_playwright().start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_connection.py", line 182, in run
    await self._transport.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_transport.py", line 140, in connect
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_transport.py", line 128, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 491, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

[2022-05-01 14:18:05,140 nonebot] INFO: Message 1349497962 is ignored
2022-05-01 14:18:05 INFO Message 1349497962 is ignored
2022-05-01 14:18:09 INFO received event: meta_event.heartbeat
![image](https://user-images.githubusercontent.com/97965580/166134758-fe9d3a73-6bed-413d-8157-6bdf1375af1e.png)

**Comment by MeetWq** [comment]
可以试试升级 `uvicorn ` 包的版本，不行的话我就不知道了，只能建议你换 ubuntu 了

另外 nb1 和 nb2 可能有区别，建议去 hoshinobot-plugin-ddcheck 提问

**Comment by SanaChitose** [comment]
> 可以试试升级 `uvicorn ` 包的版本，不行的话我就不知道了，只能建议你换 ubuntu 了
> 
> 另外 nb1 和 nb2 可能有区别，建议去 hoshinobot-plugin-ddcheck 提问

已尝试更新uvicorn，没有效果

**Comment by SanaChitose** [comment]
本心佬那边没有开issue，我已经尽力在联系他……
目前初步怀疑和环境有关，我在Windows10本机上可以正常运行，Windows server的服务器上报同样的错误。

**Comment by MeetWq** [comment]
可以单独加载这个插件试试，说不定是和别的插件有冲突
目前已知如果用了 `bilibili_api` 可能会有问题

**Comment by SanaChitose** [comment]
> 可以单独加载这个插件试试，说不定是和别的插件有冲突 目前已知如果用了 `bilibili_api` 可能会有问题

感谢大佬回复！经过排查发现居然和我用的涩图插件冲突（？
目前还在研究中

**Comment by benx1n** [comment]
不好意思之前Fork完仓库忘记打开issue= =，给您这边添麻烦了 @MeetWq 
从Traceback的信息只能看出是asyncio的报错，导致的原因还挺多的，看您排查的结果是单独开启插件时正常，和某个涩图插件一起使用就会报错，具体是和哪个插件冲突了呢？@SanaChitose 
 接下来您可以移步这边讨论benx1n/hoshinobot-plugin-ddcheck#1

**Comment by benx1n** [comment]
已修复，请拉取最新代码重装依赖后尝试
