### ISSUE TITLE
查成分报错：出错了，请稍后再试

### ISSUE THREAD

**Issue by Lyttr** [noneplugin/nonebot-plugin-ddcheck#7]
/查成分11073
[WARNING] nonebot_plugin_ddcheck | Traceback (most recent call last):
  File "D:\python\lib\site-packages\nonebot_plugin_ddcheck\__init__.py", line 33, in _
    res = await get_reply(text)
  File "D:\python\lib\site-packages\nonebot_plugin_ddcheck\data_source.py", line 158, in get_reply
    vtb_list = await get_vtb_list()
  File "D:\python\lib\site-packages\nonebot_plugin_ddcheck\data_source.py", line 82, in get_vtb_list
    await update_vtb_list()
  File "D:\python\lib\site-packages\nonebot_plugin_ddcheck\data_source.py", line 37, in update_vtb_list
    result = resp.json()
  File "D:\python\lib\site-packages\httpx\_models.py", line 1515, in json
    return jsonlib.loads(self.text, **kwargs)
  File "D:\python\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
请问是什么原因？

**Comment by MeetWq** [comment]
应该是网络问题，可以多试几次
