### ISSUE TITLE
安装后报错

### ISSUE THREAD

**Issue by sakurayun** [noneplugin/nonebot-plugin-ddcheck#8]
```
F:\nonebot\chengfenji>nb run
05-12 01:12:29 [SUCCESS] nonebot | NoneBot is initializing...
05-12 01:12:29 [INFO] nonebot | Current Env: dev
05-12 01:12:29 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'fastapi_reload': True}
05-12 01:12:29 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
05-12 01:12:29 [SUCCESS] nonebot | Succeeded to import "nonebot.plugins.echo"
05-12 01:12:29 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_ddcheck"
05-12 01:12:29 [SUCCESS] nonebot | Running NoneBot...
05-12 01:12:29 [DEBUG] nonebot | Loaded adapters: OneBot V11
05-12 01:12:29 [INFO] uvicorn | Will watch for changes in these directories: ['F:\\nonebot\\chengfenji']
05-12 01:12:29 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
05-12 01:12:29 [INFO] uvicorn | Started reloader process [5148] using watchgod
05-12 01:12:30 [WARNING] uvicorn | The --reload flag should not be used in production on Windows.
05-12 01:12:30 [SUCCESS] nonebot | NoneBot is initializing...
05-12 01:12:30 [INFO] nonebot | Current Env: dev
05-12 01:12:30 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'fastapi_reload': True}
05-12 01:12:30 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
05-12 01:12:30 [SUCCESS] nonebot | Succeeded to import "nonebot.plugins.echo"
05-12 01:12:31 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_ddcheck"
05-12 01:12:31 [INFO] uvicorn | Started server process [4668]
05-12 01:12:31 [INFO] uvicorn | Waiting for application startup.
C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\site-packages\apscheduler\util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
05-12 01:12:31 [INFO] nonebot_plugin_apscheduler | Scheduler Started
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Connection.run() done, defined at C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py:191> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py", line 198, in run
    await self._transport.connect()
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_transport.py", line 140, in connect
    raise exc
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_transport.py", line 128, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1676, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
05-12 01:12:31 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 518, in __aenter__
    await self._router.startup()
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 598, in startup
    await handler()
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 27, in init
    browser = await get_browser(**kwargs)
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 40, in get_browser
    return _browser or await init(**kwargs)
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 26, in init
    _playwright = await async_playwright().start()
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py", line 198, in run
    await self._transport.connect()
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_transport.py", line 140, in connect
    raise exc
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_transport.py", line 128, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1676, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\yuner\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

05-12 01:12:31 [ERROR] uvicorn | Application startup failed. Exiting.
```

系统：windows server 2022
Python版本：3.9.11
pip 版本22.0.4

**Comment by MeetWq** [comment]
需要把 `fastapi_reload` 设为 `False`
参考：https://v2.nonebot.dev/docs/tutorial/choose-driver#fastapi_reload
